apiVersion: v1
kind: Pod
metadata:
  name: nginx # Name of the Pod
spec:
  containers:
    - name: nginx # Name of the container
      image: nginx:latest # Nginx container image
      ports:
        - containerPort: 80 # Port to expose in the container
