apiVersion: v1
kind: Service
metadata:
  name: my-service # Name of the service
spec:
  type: NodePort # Expose the service externally using NodePort
  selector:
    app: nginx # Select pods with the label "app: nginx"
  ports:
    - port: 80 # Port exposed by the service
      targetPort: 80 # Port on pods to forward traffic to
      nodePort: 30007 # Port to access the service externally on each node
